

version: '3'

services:

  gola:
    build: .
    container_name: golang
    # command: go run ./cmd/api
    ports:
      - 8080:8080
    environment:
      - PORT=5432
      - DATABASE_URL=postgres://alikhan:pa55word@postgres:5432/alikhan?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres:latest
    container_name: pgdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: alikhan
      POSTGRES_PASSWORD: pa55word
      POSTGRES_DB: alikhan
    volumes:
      - type: volume
        source: pgdbdata
        target: /var/lib/postgres/
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120


volumes:
  pgdbdata: null